apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth
spec:
  chain:
    middlewares:
      - name: traefik-https-redirect@kubernetescrd
      - name: oauth-errors
      - name: oauth-forward
      # - name: oauth-autodetect
---
# https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#configuring-for-use-with-the-traefik-v2-forwardauth-middleware
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth-headers
  namespace: auth
spec:
  headers:
    sslRedirect: true
    stsSeconds: 315360000
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    sslHost: ${DOMAIN}
    stsIncludeSubdomains: true
    stsPreload: true
    frameDeny: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth-errors
  namespace: auth
spec:
  errors:
    status:
      - "401-403"
    service:
      name: oauth2-proxy
      namespace: auth
      port: 80
    query: "/oauth2/sign_in?rd={url}"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth-forward
  namespace: auth
spec:
  forwardAuth:
    address: https://auth.${DOMAIN}/oauth2/auth
    trustForwardHeader: true
    # tls:
    #   caSecret: traefik-cert-prod
#     # tls:
#     # insecureSkipVerify: true #
#     authResponseHeaders:
#       - X-Auth-Request-Access-Token
#       - Authorization
#       # - X-Auth-Request-User #
#       - Set-Cookie

# https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#configuring-for-use-with-the-traefik-v2-forwardauth-middleware
# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: oauth
#   namespace: traefik
# spec:
#   forwardAuth:
#     address: https://auth.${DOMAIN}/oauth2/auth_or_start
#     trustForwardHeader: true
# ---
# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: oauth-autodetect
# spec:
#   contentType:
#     autoDetect: true
# ---
