version: "3"

tasks:
  default:
    cmds:
      - task: init:pre
      - task: init:post

  deploy:
    silent: true
    dotenv:
      - ".env"
    cmds:
      - echo "re-deploy..."
      - flux uninstall -s
      - k3s-uninstall.sh && rmdir /var/lib/rancher
      - curl -sfL https://get.k3s.io | sh -s - --disable=traefik
      - curl -s https://fluxcd.io/install.sh | sudo bash
      - task: init:pre
      - task: init:post

  init:pre:
    # prompt: "Pre-initing..."
    silent: true
    dotenv:
      - ".env"
    cmds:
      - echo "Setting up secrets"

      - kubectl create ns external-secrets --dry-run=client -o yaml | kubectl apply -f -
      - |
        kubectl create secret generic gcp -n external-secrets \
          --from-file=credentials=scripts/secrets/google_cloud/account.json \
          -o yaml --dry-run=client | kubectl apply -f -

      - kubectl create ns flux-system --dry-run=client -o yaml | kubectl apply -f -
      - |
        kubectl create configmap variables-config -n flux-system \
          --from-literal=DOMAIN=$DOMAIN \
          --from-literal=EMAIL=$EMAIL \
          --from-literal=GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT \
          -o yaml --dry-run=client | kubectl apply -f -

      - flux check --pre

  init:post:
    # prompt: "Post-initing..."
    silent: true
    dotenv:
      - ".env"
    cmds:
      - echo "Setting up FluxCD"
      - |
        flux bootstrap github \
          --owner=$GITHUB_USER \
          --repository=$GITHUB_REPO \
          --branch=main \
          --path=clusters/production \
          --personal \
          --components-extra=image-reflector-controller,image-automation-controller \
          --version=latest \
          --verbose \
          --private=true \
          --token-auth # --context=staging
      # - sleep 3
      # - kill -9 $PPID
      # - watch flux get kustomizations

  init:k3s:
    prompt: "k3s initialization"
    silent: true
    dotenv:
      - ".env"
    cmds:
      - echo "Setting up k3s"
      - curl -sfL https://get.k3s.io | sh -s - --disable=traefik
      - echo "fs.inotify.max_user_instances=512" | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - echo 'ulimit -n 4096' >> ~/.bashrc # promtail - make file target manager: too many open files
      - echo 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml' >> ~/.bashrc
      - source ~/.bashrc

      - echo "Setting up FluxCD"
      - curl -s https://fluxcd.io/install.sh | sudo bash
