version: "3"

tasks:
  default:
    deps:
      - init:pre
      - init:post

  deploy:
    silent: true
    dotenv:
      - ".env"
    cmds:
      - echo "re-deploy..."
      - flux uninstall -s
      - k3s-uninstall.sh && rmdir /var/lib/rancher
      - curl -sfL https://get.k3s.io | sh -s - --disable=traefik
      - curl -s https://fluxcd.io/install.sh | sudo bash
      - task

  init:k3s:
    prompt: "k3s initialization"
    silent: true
    dotenv:
      - ".env"
    cmds:
      - echo "Setting up k3s"
      - curl -sfL https://get.k3s.io | sh -s - --disable=traefik
      - echo "fs.inotify.max_user_instances=512" | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - echo 'ulimit -n 4096' >> ~/.bashrc # promtail - make file target manager: too many open files
      - echo 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml' >> ~/.bashrc
      - source ~/.bashrc

      - echo "Setting up FluxCD"
      - curl -s https://fluxcd.io/install.sh | sudo bash

  init:pre:
    # prompt: "Pre-initing..."
    silent: true
    dotenv:
      - ".env"
    cmds:
      - echo "Setting up secrets"

      - kubectl create ns flux-system --dry-run=client -o yaml | kubectl apply -f -
      - kubectl create ns auth --dry-run=client -o yaml | kubectl apply -f -
      - |
        kubectl create secret generic oidc-auth \
        --from-literal=client-id=$GITHUB_CLIENT_ID \
        --from-literal=client-secret=$GITHUB_CLIENT_SECRET \
        --from-literal=cookie-secret=$OIDC_COOKIE_SECRET \
        --from-literal=oidc-secret=$OIDC_CLIENT_SECRET \
        -n auth

      - kubectl create ns cert-manager --dry-run=client -o yaml | kubectl apply -f -
      - kubectl create secret generic cloudflare-api-key --from-literal=api-key=$CLOUDFLARE_API_KEY -n cert-manager
      - kubectl create ns traefik --dry-run=client -o yaml | kubectl apply -f -
      - kubectl create secret generic basic-auth-key --from-literal=auth=$BASIC_AUTH_KEY -n traefik

      # kubectl create secret docker-registry docker-registry-key \
      #   --docker-server=https://index.docker.io/v1/ \
      #   --docker-username=[DockerHub username] \
      #   --docker-password=[DockerHub access token] \
      #   --docker-email=[email address]

      - |
        kubectl create configmap variables-config \
          --from-literal=DOMAIN=$DOMAIN \
          --from-literal=EMAIL=$EMAIL \
          --from-literal=CLOUDFLARE_ZONE_ID=$CLOUDFLARE_ZONE_ID \
          -n flux-system

      - flux check --pre

  init:post:
    # prompt: "Post-initing..."
    silent: true
    dotenv:
      - ".env"
    cmds:
      - echo "Setting up FluxCD"
      - |
        flux bootstrap github \
          --owner=$GITHUB_USER \
          --repository=$GITHUB_REPO \
          --branch=main \
          --path=clusters/production \
          --personal \
          --components-extra=image-reflector-controller,image-automation-controller \
          --version=latest \
          --verbose \
          --private=true \
          --token-auth # --context=staging
