apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: selfhosted-manifests
  namespace: flux-system
spec:
  interval: 5m
  url: https://hawkkiller.github.io/selfhosted-manifests/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: chat-gpt
spec:
  releaseName: chat-gpt
  chart:
    spec:
      chart: chat-gpt
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: selfhosted-manifests
        namespace: flux-system
  interval: 15m
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: chat-gpt-value-overrides
