apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - podmonitor.yaml
  - cnpg
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: flux-grafana-dashboards
    files:
      - dashboards/traefik-dashboard.json
      - dashboards/control-plane.json
      - dashboards/cluster.json
      - dashboards/logs.json
      - dashboards/cnpg.json
    options:
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
  - name: flux-grafana-datasources
    files:
      - datasources/loki.yml
    options:
      labels:
        grafana_datasource: "true"
        app.kubernetes.io/part-of: flux
        app.kubernetes.io/component: monitoring
