apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dex
spec:
  interval: 5m
  chart:
    spec:
      chart: dex
      version: 0.6.5
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: auth
      interval: 1m
  values:
    image:
      tag: v2.31.0
    envVars:
      - name: GITHUB_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: oidc-auth
            key: client-id
      - name: GITHUB_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: oidc-auth
            key: client-secret
      - name: OIDC_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: oidc-auth
            key: oidc-secret
    config:
      # Set it to a valid URL
      issuer: https://dex.${DOMAIN}

      # See https://dexidp.io/docs/storage/ for more options
      storage:
        type: memory

      expiry:
        signingKeys: "4h"
        idTokens: "1h"
      staticClients:
        - name: "OAuth2 Proxy"
          id: oauth2-proxy
          secret: $OIDC_CLIENT_SECRET
          redirectURIs:
            # These redirect URI points to the `--redirect-url` for OAuth2 proxy.
            - "https://auth.${DOMAIN}/oauth2/callback"
      #   - name: "Weave GitOps"
      #     id: weave-gitops
      #     secret: AiAImuXKhoI5ApvKWF988txjZ+6rG3S7o6X5En
      #     redirectURIs:
      #       - "https://weave.${DOMAIN}/oauth2/callback"

      # enablePasswordDB: true
      # staticPasswords:
      #   - email: "admin@example.com"
      #     # bcrypt hash of the string "password"
      #     hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      #     username: "admin"
      #     userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: $GITHUB_CLIENT_ID
            clientSecret: $GITHUB_CLIENT_SECRET
            redirectURI: https://dex.${DOMAIN}/callback
            orgs:
              - name: zs-dmitrii

    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.kubernetes.io/target: dex.${DOMAIN}
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/service.serversscheme: https

      hosts:
        - host: dex.${DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: traefik-cert-prod
          hosts:
            - dex.${DOMAIN}
