apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc-auth
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: gcp
    kind: ClusterSecretStore
  target:
    name: oidc-auth
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: oidc-auth
