apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn
      interval: 12h
  # https://github.com/longhorn/longhorn/blob/master/chart/values.yaml
  values:
    # helmPreUpgradeCheckerJob: # ArgoCD fix
    #   enabled: false

    longhornUI:
      replicas: 1

    # defaultSettings:
    #   TODO Available: NFS, CIFS, AWS, GCP, AZURE.
    #   backupTarget: ~

    metrics:
      serviceMonitor:
        enabled: true

    allowCollectingLonghornUsageMetrics: false

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        external-dns.kubernetes.io/target: longhorn.${DOMAIN}
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: auth-oauth@kubernetescrd
      host: longhorn.${DOMAIN}
      tls: true
      tlsSecret: traefik-cert-prod
