apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-ks
  namespace: flux-system
spec:
  path: ./infrastructure/core/external-secrets/controller/
  wait: true
  prune: true
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-config
  namespace: flux-system
spec:
  path: ./infrastructure/core/external-secrets/config/
  dependsOn:
    - name: external-secrets-ks
  wait: true
  prune: true
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: variables-config
