apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homer
resources:
  - namespace.yaml
  - homer.yaml
  - ingress.yaml
configMapGenerator:
  - name: homer-dashboard
    files:
      - configs/config.yml
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/component: homer
