apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-ks
  namespace: flux-system
spec:
  path: ./infrastructure
  wait: true
  prune: true
  timeout: 25m0s
  interval: 50m0s
  # retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: variables-config
  patches:
    - target:
        kind: Kustomization
        group: kustomize.toolkit.fluxcd.io
      patch: |-
        - op: add
          path: /spec/postBuild
          value:
            substituteFrom:
              - kind: ConfigMap
                name: variables-config
              - kind: Secret
                name: variables-secret

# TODO variables-secret used by Dex, external-dns, weave-gitops
