apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: auth-idp-ks
  namespace: flux-system
  labels:
    substitute: secrets
spec:
  path: ./infrastructure/auth/dex/
  wait: true
  prune: true
  timeout: 5m0s
  interval: 10m0s
  dependsOn:
    - name: core-ks
    - name: traefik-config
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: auth-ks
  namespace: flux-system
spec:
  path: ./infrastructure/auth/oauth2-proxy/
  wait: true
  prune: true
  timeout: 5m0s
  interval: 10m0s
  dependsOn:
    - name: auth-idp-ks
  sourceRef:
    kind: GitRepository
    name: flux-system
