# https://github.com/portainer/k8s/blob/master/charts/portainer/values.yaml
# https://doc.traefik.io/traefik/routing/providers/kubernetes-ingress/

replicaCount: 1

enterpriseEdition: 
  enabled: true
  image:
    repository: portainer/portainer-ee
    tag: latest
    pullPolicy: Always

service:
  type: LoadBalancer

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls.domains.0.main: portainer.${DOMAIN}
    traefik.ingress.kubernetes.io/service.serversscheme: https
  tls:
  - secretName: traefik-cert-prod
    hosts:
    - portainer.${DOMAIN}
  hosts:
  - host: portainer.${DOMAIN}
    paths:
    - path: /
      pathType: Prefix

