apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-certificate
  namespace: flux-system
spec:
  path: ./infrastructure/networking/traefik/certificate/
  targetNamespace: traefik
  dependsOn:
    - name: cert-manager-config
  wait: true
  prune: true
  timeout: 20m0s
  interval: 40m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-ks
  namespace: flux-system
spec:
  path: ./infrastructure/networking/traefik/controller/
  targetNamespace: traefik
  dependsOn:
    - name: traefik-certificate
  wait: true
  prune: true
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-config
  namespace: flux-system
spec:
  path: ./infrastructure/networking/traefik/config/
  targetNamespace: traefik
  dependsOn:
    - name: traefik-ks
  wait: true
  prune: true
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
