# apiVersion: traefik.io/v1alpha1
# kind: Middleware
# metadata:
#   name: https-redirect-middleware
#   namespace: traefik
# spec:
#   redirectScheme:
#     scheme: https
#     permanent: true
# ---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: basic-auth-middleware
  namespace: traefik
spec:
  basicAuth:
    removeHeader: true
    secret: basic-auth-secret