apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-ks
  namespace: flux-system
spec:
  path: ./infrastructure/networking/cert-manager/controller/
  targetNamespace: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1h
  prune: true
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  path: ./infrastructure/networking/cert-manager/config/
  targetNamespace: cert-manager
  dependsOn:
    - name: cert-manager-ks
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1h
  prune: true
