apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-ks
  namespace: flux-system
spec:
  path: ./infrastructure/networking/cert-manager/controller/
  dependsOn:
    - name: external-secrets-config
  wait: true
  prune: true
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  path: ./infrastructure/networking/cert-manager/config/
  dependsOn:
    - name: cert-manager-ks
  wait: true
  prune: true
  timeout: 20m0s
  interval: 40m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
