apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  path: ./apps/staging
  dependsOn:
    - name: infra-configs
  wait: true
  prune: true
  timeout: 20m
  interval: 24h
  sourceRef:
    kind: GitRepository
    name: flux-system
