apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: variables-secret
  namespace: flux-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gcp
    kind: ClusterSecretStore
  data:
    - secretKey: GITHUB_ORG
      remoteRef:
        key: oidc-auth
        property: client-org

    - secretKey: CLOUDFLARE_ZONE_ID
      remoteRef:
        key: cloudflare
        property: zone-id

  # target:
  #   name: variables-secret
  #   creationPolicy: Owner
  #   template:
  #     type: Opaque
  #     data:
  #       GITHUB_ORG: '{{ index . "client-org" | toString }}'
  #       CLOUDFLARE_ZONE_ID: '{{ index . "zone-id" | toString }}'
  # dataFrom:
  #   - extract:
  #       key: oidc-auth
  #   - extract:
  #       key: cloudflare
