---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp
            key: credentials
            namespace: external-secrets
      projectID: ${GOOGLE_CLOUD_PROJECT}
# https://external-secrets.io/latest/api/clusterexternalsecret/

