apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app external-dns
spec:
  interval: 15m
  chart:
    spec:
      chart: external-dns
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: cert-manager
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # https://github.com/kubernetes-sigs/external-dns/blob/master/charts/external-dns/values.yaml
  values:
    fullnameOverride: *app
    provider: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-key
            key: api-key
    extraArgs:
      - --zone-id-filter=${CLOUDFLARE_ZONE_ID}
      - --annotation-filter=external-dns.kubernetes.io/target
      - --cloudflare-proxied
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --cloudflare-dns-records-per-page=5000
    # policy: sync
    sources: ["crd", "ingress", "service"]
    # txtPrefix: k8s.
    # txtOwnerId: default
    domainFilters:
      - "${DOMAIN}"
    # serviceMonitor:
    # enabled: true
    # TODO podAnnotations:
    #   secret.reloader.stakater.com/reload: cloudflare-api-key
