apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: gcp
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-key
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: cloudflare
