apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
  namespace: flux-system
spec:
  path: ./infrastructure/monitoring/controllers
  wait: true
  prune: true
  timeout: 5m0s
  interval: 10m0s
  dependsOn:
    - name: auth-ks
  retryInterval: 2m
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-configs
  namespace: flux-system
spec:
  path: ./infrastructure/monitoring/configs
  dependsOn:
    - name: monitoring-controllers
  wait: true
  prune: true
  timeout: 5m0s
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
