apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 1h
  chart:
    spec:
      version: "*"
      chart: external-secrets
      sourceRef:
        kind: HelmRepository
        name: external-secrets
      interval: 1h
  # values:
