apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cnpg
spec:
  interval: 1h
  chart:
    spec:
      version: "*"
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cnpg
      interval: 1h
  # https://github.com/cloudnative-pg/charts/blob/main/charts/cloudnative-pg/values.yaml
  # values:
