apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-auth
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gcp
    kind: ClusterSecretStore
  target:
    name: postgres-auth-key
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: app
        password: "{{ .password | toString }}"
  dataFrom:
    - extract:
        key: basic-auth
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-su
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gcp
    kind: ClusterSecretStore
  target:
    name: postgres-su-key
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: postgres
        password: "pg^{{ .password | toString }}"
  dataFrom:
    - extract:
        key: basic-auth
