apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-ks
  namespace: flux-system
spec:
  path: ./infrastructure/core/
  wait: true
  prune: true
  timeout: 15m0s
  interval: 20m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
