apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: weave-gitops
  annotations:
    metadata.weave.works/description:
      This is the Weave GitOps Dashboard. It provides
      a simple way to get insights into your GitOps workloads.
spec:
  interval: 60m
  chart:
    spec:
      chart: weave-gitops
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
      interval: 12h
  # https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/values.yaml
  values:
    ingress:
      enabled: true
      className: traefik
      annotations:
        external-dns.kubernetes.io/target: weave.${DOMAIN}
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/service.serversscheme: https
      hosts:
        - host: weave.${DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: traefik-cert-prod
          hosts:
            - weave.${DOMAIN}

    adminUser:
      create: false
    serviceAccount:
      create: true
      name: wego-cluster-admin # gitops-test-user
    # rbac:
    #   create: false
    additionalArgs:
      # https://docs.gitops.weave.works/docs/guides/anonymous-access/
      # - --insecure-no-authentication-user=gitops-test-user
      - --auth-methods=oidc

    envVars:
      - name: WEAVE_GITOPS_FEATURE_OIDC_BUTTON_LABEL
        value: "Login with ACME"

    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 512Mi
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      # runAsUser: 1000
