apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: weave-gitops
  namespace: flux-system
  annotations:
    metadata.weave.works/description: This is the source location for the Weave GitOps Dashboard's helm chart.
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/created-by: weave-gitops-cli
    app.kubernetes.io/name: weave-gitops-dashboard
    app.kubernetes.io/part-of: weave-gitops
spec:
  type: oci
  interval: 1h0m0s
  url: oci://ghcr.io/weaveworks/charts
