apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-oidc-auth
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gcp
    kind: ClusterSecretStore
  target:
    name: oidc-auth
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        clientID: weave-gitops
        clientSecret: '{{ index . "oidc-secret" | toString }}'
        issuerURL: https://dex.${DOMAIN}
        redirectURL: https://weave.${DOMAIN}/oauth2/callback
  dataFrom:
    - extract:
        key: oidc-auth
