apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: auth-ks
  namespace: flux-system
spec:
  path: ./infrastructure/auth/
  dependsOn:
    - name: core-ks
    - name: traefik-config
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1h
  prune: true
  wait: true
