# https://github.com/rancher/rancher/blob/release/v2.8/chart/templates/ingress.yaml
# https://dev.to/blakec/exploring-the-helmchart-custom-resource-in-k3s-2l52

apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rancher
  namespace: cattle-system
spec:
  chart: rancher
  repo: https://releases.rancher.com/server-charts/latest
  version: "v2.8.0-rc3"
  targetNamespace: cattle-system
  set:
    hostname: admin.dmitrii.it
    bootstrapPassword: d1479335-0bce-4881-a324-9710955a31ab
  valuesContent: |-
    ingress:
      enabled: true
      extraAnnotations: # annotations:
        kubernetes.io/ingress.class: traefik
        cert-manager.io/cluster-issuer: letsencrypt-staging
        traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
        traefik.ingress.kubernetes.io/router.tls.domains.0.main: admin.dmitrii.it
      tls:
        source: secret
        secretName: traefik-cert-staging
