apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      interval: 12h
  values:
    admissionWebhooks:
      enabled: false
    controller:
      service:
        type: "NodePort"
      #   service:
      #     type: "LoadBalancer"
      #     externalTrafficPolicy: Local
      #   extraArgs:
      #     default-ssl-certificate: "networking/${DOMAIN}-io"
      # defaultBackend:
      #   enabled: true
      #   image:
      #     repository: ghcr.io/tarampampam/error-pages
      #     tag: 2.24.0
      #   extraEnvs:
      #     - { name: TEMPLATE_NAME, value: ghost }
      #     - { name: SHOW_DETAILS, value: "false" }
