apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: auth-app
  namespace: flux-system
spec:
  targetNamespace: auth-app
  sourceRef:
    kind: OCIRepository
    name: auth-app
  interval: 1h
  retryInterval: 30s
  timeout: 5m
  path: ./
  prune: true
  wait: true
