apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: auth-app
  namespace: flux-system
spec:
  interval: 1m
  url: oci://docker.io/zsdima/auth-app
  ref:
    tag: 1.0.0-beta.2
