apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: basic-auth
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gcp
    kind: ClusterSecretStore
  target:
    name: basic-auth-key
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username | toString }}"
        password: "{{ .password | toString }}"
  dataFrom:
    - extract:
        key: basic-auth
