apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
spec:
  interval: 1h
  chart:
    spec:
      version: "*"
      chart: n8n
      sourceRef:
        kind: HelmRepository
        name: n8n
      interval: 1h
  # https://github.com/8gears/n8n-helm-chart/blob/master/values.yaml
  values:
    image:
      repository: n8nio/n8n
      tag: 1.20.0
      pullPolicy: IfNotPresent # Always
    persistence:
      enabled: true
      type: pvc
      existingClaim: n8n-pvc

    extraEnv:
      N8N_BASIC_AUTH_ACTIVE: false
      N8N_HOST: n8n.${DOMAIN}
      N8N_PORT: 80
      N8N_PROTOCOL: http
      WEBHOOK_URL: https://n8n.${DOMAIN}
      NODE_ENV: production
      TZ: UTC

    ingress:
      enabled: true
      ingressClassName: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.kubernetes.io/target: n8n.${DOMAIN}
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: traefik-basic-auth-middleware@kubernetescrd
        traefik.ingress.kubernetes.io/service.serversscheme: https
      hosts:
        - host: n8n.${DOMAIN}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: traefik-cert-prod
          hosts:
            - n8n.${DOMAIN}
